name: Auto-run package.py
on:
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs:
  run-package:
    runs-on: windows-latest
    steps:
    - name: Git long allow
      run : git config --global core.longpaths true
    - name: Git clone
      run: git clone https://github.com/Sam5440/Genshin_Impact_Teleport
    - name: Auto push
      run: |
        cd ./Genshin_Impact_Teleport
        python package.py
        cd ./zips
        git init
        git config --local user.email "Y_sam5440@outlook.com"
        git config --local user.name "Sam5440"
        git add .
        git commit --allow-empty -m "file sync"
        git branch -m master download
        git remote add origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push -u origin download -f
