name: Auto Packager
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - .gitignore
      - README.md
#      - package.py
      - LICENSE

jobs:
  run-package:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Python setup
        uses: actions/setup-python@main
        with:
          python-version: 3.10.9

      - name: Git long allow
        run : git config --global core.longpaths true

      - name: Checkout from ${{ github.repository }}/commit/${{ github.sha }}
        uses: actions/checkout@main

      - name: Package files
        run: python package.py

      - name: Push to download branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: download
          FOLDER: zips
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
